// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview A personalized course recommendation AI agent.
 *
 * - personalizedCourseRecommendation - A function that handles the course recommendation process.
 * - PersonalizedCourseRecommendationInput - The input type for the personalizedCourseRecommendation function.
 * - PersonalizedCourseRecommendationOutput - The return type for the personalizedCourseRecommendation function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const PersonalizedCourseRecommendationInputSchema = z.object({
  careerGoals: z.string().describe('The career goals of the prospective student.'),
  educationalBackground: z.string().describe('The educational background of the prospective student.'),
  interests: z.string().describe('The interests of the prospective student.')
});
export type PersonalizedCourseRecommendationInput = z.infer<typeof PersonalizedCourseRecommendationInputSchema>;

const PersonalizedCourseRecommendationOutputSchema = z.object({
  courseRecommendations: z.array(z.string()).describe('A list of personalized course recommendations.'),
  reasoning: z.string().describe('The reasoning behind the course recommendations.')
});
export type PersonalizedCourseRecommendationOutput = z.infer<typeof PersonalizedCourseRecommendationOutputSchema>;

export async function personalizedCourseRecommendation(input: PersonalizedCourseRecommendationInput): Promise<PersonalizedCourseRecommendationOutput> {
  return personalizedCourseRecommendationFlow(input);
}

const prompt = ai.definePrompt({
  name: 'personalizedCourseRecommendationPrompt',
  input: {schema: PersonalizedCourseRecommendationInputSchema},
  output: {schema: PersonalizedCourseRecommendationOutputSchema},
  prompt: `You are an expert academic advisor specializing in recommending courses to prospective students.

You will use the career goals, educational background and interests to recommend courses to the student. You will provide a list of courses and the reasoning behind the recommendations.

Career Goals: {{{careerGoals}}}
Educational Background: {{{educationalBackground}}}
Interests: {{{interests}}}`,  
});

const personalizedCourseRecommendationFlow = ai.defineFlow(
  {
    name: 'personalizedCourseRecommendationFlow',
    inputSchema: PersonalizedCourseRecommendationInputSchema,
    outputSchema: PersonalizedCourseRecommendationOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
