
export const testimonials = [
    { name: "Riddhi Mestry", course: "Data Analysis", story: "Primezone Computer Education is the best institute for programming, computer fundamentals, and data analysis. I gained real confidence working with Python, SQL, and Advanced Excel, and the practical exercises helped me build career-ready skills." },
    { name: "Madan Sunar", course: "Programming", story: "Best computer class for learning fundamentals like MS Word, Excel, PowerPoint, and also programming. Their training in C/C++, Python and Java gives beginners a clear path to advanced development." },
    { name: "Nirmayee Khot", course: "DIA & Digital Marketing", story: "Excellent faculty and a positive learning experience with lots of practical learning. Teachers explain things step-by-step — from DIA basics to modern topics like Digital Marketing and Data Analytics." },
    { name: "Anushka Gawade", course: "Web Development", story: "Great teaching across all courses — from Word, Excel, PPT to advanced subjects such as React, Django and PowerBI. The lessons are easy to follow and full of hands-on examples." },
    { name: "Bablu Kumar", course: "Vocational Courses", story: "Very good class 👍. I learned both basic computer skills and useful vocational courses like Tally + GST and SQL, which are immediately useful for jobs." },
    { name: "Fatima Salmani", course: "Graphic Designing & Data Analytics", story: "Best class! Teaching is clear and structured. They offer everything from Graphic Designing to Data Analytics, so it’s perfect for beginners and aspirants alike." },
    { name: "Yash Tripathi", course: "Data Analytics", story: "Best class in Jogeshwari. Supportive staff and quality training in PowerBI, Data Analytics, and practical courses that prepare you for real work." },
    { name: "Heer Jain", course: "DIA & Advanced Excel", story: "One of the best computer education institutes in Jogeshwari East. They cover everything — DIA (Word, Excel, PPT), Advanced Excel, and development courses like Python and Java." },
    { name: "Kesar Menge", course: "Advanced Excel & SQL", story: "Best computer coaching classes 🫶. I especially appreciated the Advanced Excel and SQL training — very hands-on and job-oriented." },
    { name: "Vivek Singh", course: "Tally & Graphic Designing", story: "Teaching quality is excellent. All teachers are helpful and friendly, and they cover a wide variety of courses including Tally + GST, Graphic Designing, and programming." },
    { name: "Amey Patel", course: "Programming", story: "Great class! The training is practical — I got hands-on experience in Python, HTML–CSS, and Excel, which boosted my confidence quickly." },
    { name: "Siddhesh Agre", course: "Web Development", story: "Fantastic experience — I learned many courses here. From DIA basics to Java, Django and React, the instructors are patient and thorough." },
    { name: "Alfiya Shaikh", course: "Advanced Excel & PowerBI", story: "Faculty is very helpful and kind. This is the best place for learners — they explained concepts in detail, especially Advanced Excel and PowerBI." },
    { name: "Shaikh Iqra", course: "SQL & Tally", story: "Teachers are very helpful and explain everything in an easy way. I gained strong skills in SQL, Tally + GST, and AutoCAD basics." },
    { name: "Jyoti Nagvekar", course: "Data Analytics & Python", story: "Excellent computer classes, friendly teachers, and a great atmosphere. Ideal for beginners (Word, Excel, PPT) and those seeking advanced courses like Data Analytics and Python." },
    { name: "Priyal Dalvi", course: "Digital Marketing & Graphic Designing", story: "Looking for the best computer institute? Visit Primezone. Knowledgeable teachers, practical courses (like Digital Marketing and Graphic Designing), and a supportive learning environment." },
    { name: "Trupti Shinde", course: "Basic Computer Course", story: "I am pursuing a Basic Computer Course at Primezone. The curriculum included MS Word, Excel, PowerPoint, plus introductions to Advanced Excel and PowerBI — very useful." },
    { name: "Yash Jangam", course: "Web Development", story: "Very excellent — perfect for computer education. I learned Python, SQL, and React, which have been extremely helpful for my projects and job prospects." },
    { name: "Shaila Gawade", course: "DIA & Tally", story: "Excellent teaching 👍👍. The class covers many courses like DIA, Advanced Excel, and Tally + GST. My overall experience was very positive and practical 🤗." },
    { name: "Shreeya Aras", course: "DFAM", story: "I joined a DFAM course here and had a great experience. Polite, helpful staff and courses that expand into Data Analytics and programming as you progress." },
    { name: "Prathamesh Salvi", course: "DFAM", story: "Such a nice class with well-supporting teaching staff. I’m doing DFAM — totally worth it — and the institute strongly supports learning Excel, Tally + GST, and programming essentials." },
    { name: "Nandini", course: "DIA", story: "A very good class where we learned a lot. The sessions balance theory and practice well, covering DIA basics up to more advanced tools." },
    { name: "Shaikh Afsha", course: "DIA & Advanced Excel", story: "I am doing DIA. I like the staff’s friendly teaching style — they teach clearly and make even technical topics like Advanced Excel approachable." },
    { name: "Saania Shaikh", course: "Computer Basics", story: "Teachers are very supportive. They helped me understand everything from Word and Excel basics to more career-oriented courses." },
    { name: "Atharva Shigawan", course: "Tally", story: "I started with zero knowledge and now I’m a Tally expert. The practical approach to Tally + GST made learning fast and effective." },
    { name: "Anway Rane", course: "SQL", story: "I began SQL with no prior experience; after completing the course I can confidently work with databases and queries. The SQL training is hands-on and clear." },
    { name: "Uzma Sufi", course: "Python, SQL, & PowerBI", story: "Very good experience. Teaching style is excellent and the faculty is experienced — especially strong in technical courses like Python, SQL, and PowerBI." },
    { name: "Harsh Warang", course: "Programming", story: "The teaching style inspired me to enjoy learning. Class environment is motivating and teachers are great — they explain everything, whether it’s programming or office automation." },
    { name: "Gaurav Gohil", course: "Graphic & Digital Marketing", story: "Nice — I learned many practical skills here and the overall experience was excellent. Courses like Graphic Designing and Digital Marketing are well structured." },
    { name: "Mohit Yadav", course: "Skill Building", story: "✨Primezone Computer Education Centre – Goregaon Branch✨ is best for skill-building. Trainers teach smoothly and the practical labs helped me master tools quickly." },
    { name: "Falak Shaikh", course: "DIA & PowerBI", story: "Best computer class — friendly environment and clear lessons. Good mix of basic DIA topics and advanced options like PowerBI." },
    { name: "Pravin Patel", course: "MS Office", story: "Good teaching — trainers are patient and cover topics thoroughly, from MS Office to job-oriented courses." },
    { name: "Sara Shaikh", course: "Diploma in Accounting", story: "All teaching staff were cooperative. I’m doing the Diploma in Accounting, which is wonderful — practical and relevant for placements." },
    { name: "Rishabh Yadav (Sonal)", course: "Skill Development", story: "My experience here is great 👍. The institute focuses on real skills and offers a variety of courses that helped me upskill quickly." },
    { name: "Afreen Khilaniya", course: "DIA", story: "My experience was great. Teachers are friendly and supportive, and the classes (from DIA to advanced subjects) are well organized." },
    { name: "Preksha Patil", course: "Computer Class", story: "I thoroughly enjoyed this class and gained much knowledge. Instructors are kind and competent — good for both beginners and advanced learners." },
    { name: "Samanvi Acharya", course: "Data Analytics", story: "The computer class was comprehensive and covered everything I hoped to learn. The instructor was clear and practical, covering Word, Excel, and introductory Data Analytics." },
    { name: "Shweta Kandu", course: "Computer Course", story: "Studying at Primezone was a great experience — friendly and cooperative staff, and courses that are both practical and career-oriented." },
    { name: "Ganesh Rane", course: "Office Automation", story: "I took Office Automation and Advanced Excel at Primezone and really benefited. The training is job-focused and helped me improve productivity significantly." },
    { name: "Dhrisha Shetty", course: "Data Analysis", story: "Best class with good faculty to learn data analysis course. Currently learning Python, Power BI, Tableau and Advanced Excel. The trainers are very professional and flexible learning hours available." },
    { name: "Abhijeet Shetty", course: "Data Analytics", story: "Best faculty for Data Analytics course. Currently I am pursuing Python course. The quality of content and the training given is best." },
    { name: "Shubham Zore", course: "Tally", story: "I am Tally student in Primezone in Vile Parle branch. Teachers are helpful, cooperative and friendly." },
    { name: "Kevan Fernandes", course: "MS Office & Tally", story: "I am student of Primezone computer institution. I have taken Word, PowerPoint, Excel, Advanced Excel, Tally Prime with GST..." },
    { name: "Keith Fernandes", course: "MS Office", story: "I am student of Primezone. I am currently pursuing MS Office, Excel, PPT, Advanced Excel, etc. The management is great, easy to be learned by the faculty. Amazing experience till date." },
    { name: "Arshad Shaikh", course: "Review", story: "" },
    { name: "Siddhesh Agre", course: "JavaScript", story: "It's a best experience for JavaScript and many more courses." },
    { name: "Ananya Paigankar", course: "Coding", story: "Great place to learn coding. 10/10" },
    { name: "Samkit Rambhia", course: "General", story: "Best faculty." },
    { name: "Sanchita Sail", course: "General", story: "I’m in Vile Parle branch. Teachers are very helpful and supportive, they clear all doubts of us." },
    { name: "Sonam Singh", course: "Review", story: "" },
    { name: "Jaiswar Jii (Itz Denny)", course: "Diploma in Financial Accounting", story: "I'm doing DFA course (Diploma in Financial Accounting) in Primezone Computer Institute which is located in Vile Parle..." },
    { name: "UP 62 Sanjay Jaiswar K", course: "Diploma in Financial Accounting", story: "I have taken DFA (Diploma in Financial Accounting). This is an amazing institute, they have nice teachers teaching the course. I got best discount by Primezone Computer Institute." },
    { name: "Sachin Kumar", course: "Diploma in Financial Accounting", story: "I’m taking the DFA (Diploma in Financial Accounting) in Primezone Computer Education in Vile Parle East." },
  ];

    